# fly.toml app configuration file generated for food-track on 2023-05-30T17:43:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "food-track"
primary_region = "ewr"

[deploy]
  release_command = "sh /release.sh"
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  SURPRESS_EMAIL_SEND = 0