# fly.toml app configuration file generated for food-track on 2023-05-01T19:39:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "food-track"
primary_region = "ewr"


[deploy]
  release_command = "alembic upgrade head"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
