"""Added activty_level column to daily_overview

Revision ID: 5683fbb7ff9c
Revises: 93270bad16f4
Create Date: 2023-11-11 00:18:17.608385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5683fbb7ff9c'
down_revision = '93270bad16f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_overview', sa.Column('activity_level', sa.Float(), nullable=True))
    op.alter_column('food_log', 'serving_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_log', 'serving_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('daily_overview', 'activity_level')
    # ### end Alembic commands ###
