"""add fdc_id column to food

Revision ID: 7f3618007c3b
Revises: 3f2cea6008b1
Create Date: 2023-04-02 23:04:58.222177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3618007c3b'
down_revision = '3f2cea6008b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('fdc_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'fdc_id')
    # ### end Alembic commands ###
