"""init

Revision ID: 839a91d090f9
Revises: 
Create Date: 2023-04-02 22:32:20.240408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839a91d090f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('email', sa.VARCHAR(length=320), nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(length=1024), nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), nullable=False),
        sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
        sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('daily_overview',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('profile_id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=True),
        sa.Column('actual_weight', sa.FLOAT(), nullable=True),
        sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_overview_id', 'daily_overview', ['id'], unique=False)
    op.create_table('serving_size',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('food_id', sa.INTEGER(), nullable=False),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('calories', sa.INTEGER(), nullable=True),
        sa.Column('fats', sa.INTEGER(), nullable=True),
        sa.Column('carbs', sa.INTEGER(), nullable=True),
        sa.Column('protein', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_serving_size_id', 'serving_size', ['id'], unique=False)
    op.create_table('recipe',
        sa.Column('finished_food', sa.INTEGER(), nullable=True),
        sa.Column('ingredient', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['finished_food'], ['food.id'], ),
        sa.ForeignKeyConstraint(['ingredient'], ['food.id'], )
    )
    op.create_table('profile',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('start_date', sa.DATE(), nullable=True),
        sa.Column('start_weight', sa.FLOAT(), nullable=True),
        sa.Column('goal_weight', sa.FLOAT(), nullable=True),
        sa.Column('sex', sa.VARCHAR(), nullable=True),
        sa.Column('birthdate', sa.DATE(), nullable=True),
        sa.Column('height', sa.INTEGER(), nullable=True),
        sa.Column('lbs_per_week', sa.FLOAT(), nullable=True),
        sa.Column('activity_level', sa.FLOAT(), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_id', 'profile', ['id'], unique=False)
    op.create_table('food',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('brand', sa.VARCHAR(), nullable=True),
        sa.Column('name', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_id', 'food', ['id'], unique=False)
    op.create_table('food_log',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=True),
        sa.Column('food_id', sa.INTEGER(), nullable=False),
        sa.Column('serving_size_id', sa.INTEGER(), nullable=False),
        sa.Column('serving_amount', sa.INTEGER(), nullable=True),
        sa.Column('profile_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['serving_size_id'], ['serving_size.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_log_id', 'food_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_log_id', table_name='food_log')
    op.drop_table('food_log')
    op.drop_index('ix_food_id', table_name='food')
    op.drop_table('food')
    op.drop_index('ix_profile_id', table_name='profile')
    op.drop_table('profile')
    op.drop_table('recipe')
    op.drop_index('ix_serving_size_id', table_name='serving_size')
    op.drop_table('serving_size')
    op.drop_index('ix_daily_overview_id', table_name='daily_overview')
    op.drop_table('daily_overview')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
