"""Added user_id column to food

Revision ID: 93270bad16f4
Revises: beaa24779288
Create Date: 2023-09-11 19:42:56.244316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93270bad16f4'
down_revision = 'beaa24779288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('food_log', 'serving_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_log', 'serving_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'user_id')
    # ### end Alembic commands ###
